config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "projects#index"
  resources :projects do
    resources :issues do
      member do
        post :add_comment
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :issue
end

app/models/issue.rb
class Issue < ApplicationRecord
  STATUS = { active: 0, on_hold: 1, resolved: 2, closed: 3 }
  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :title, presence: true

  enum status: STATUS
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :issues, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy


  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit( :sign_up, keys: %i[ first_name last_name] )
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :add_comment
  before_action :fetch_project
  before_action :fetch_issue, only: [:edit, :update, :destroy, :add_comment]

  def new
    @issue = Issue.new
  end

  def create
    issue = @project.issues.new(issue_params)
    if issue.save
      flash[:notice] = 'Issue successfully created'
      redirect_to project_path(@project)
    else
      flash[:error] = issue.errors.full_messages.compact * ' and '
      redirect_to new_project_issue_path(@project)
    end
  end

  def update
    if @issue.update(issue_params)
      flash[:notice] = 'Issue successfully updated'
      redirect_to project_path(@project)
    else
      flash[:error] = @issue.errors.full_messages.compact * ' and '
      redirect_to edit_project_issue_path(@project, @issue)
    end
  end

  def destroy
    @issue.destroy
    flash[:notice] = 'Issue successfully deleted'
    redirect_to project_path(@project)
  end

  def add_comment
    @comment = @issue.comments.create(comments_params.merge(user_id: current_user.id))
    render json: {description: @comment.description, date: @comment.created_at.strftime("%Y-%m-%d %H:%M")}
  end

  private

  def fetch_project
    @project = current_user.projects.find_by(id: params[:project_id])
    if @project.nil?
      flash[:error] = 'Project not found'
      redirect_to root_path
      return
    end
  end

  def fetch_issue
    @issue = @project.issues.find_by(id: params[:id])
    if @issue.nil?
      flash[:error] = 'Issue not found'
      redirect_to root_path
      return
    end
  end

  def comments_params
    params.require(:comment).permit(:description)
  end

  def issue_params
    params[:issue][:status] = params[:issue][:status].to_i if params[:issue][:status].present?
    params.require(:issue).permit(:title, :assign_to, :status, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :fetch_project, except: [:index, :new, :create]

  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    project = current_user.projects.new(project_params)
    if project.save
      flash[:notice] = 'Project successfully created'
      redirect_to projects_path
    else
      flash[:error] = project.errors.full_messages.compact * ' and '
      redirect_to new_project_path
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project successfully updated'
      redirect_to projects_path
    else
      flash[:error] = @project.errors.full_messages.compact * ' and '
      redirect_to edit_project_path(@project)
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = 'Project successfully deleted'
    else
      flash[:notice] = 'Unable to delete this project'
    end
    redirect_to projects_path
  end

  private

  def fetch_project
    @project = current_user.projects.find_by(id: params[:id])
    if @project.nil?
      flash[:error] = 'Project not found'
      redirect_to root_path
      return
    end
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/_comment.html.erb
<div class="comment_row">
  <div class="time"><%=comment.created_at.strftime("%Y-%m-%d %H:%M")%></div>
  <div class="text"><%=comment.description%></div>
</div>
 

app/views/issues/_form.html.erb
<%= form_for [@project, @issue], :html => {:class => "issue_form"} do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :assign_to %>
    <%= f.text_field :assign_to %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(Issue::STATUS.map{|k,v| [k.to_s.humanize, v]}, Issue::STATUS[@issue.status.to_sym]), {} %>
  </div>
  <%= f.submit 'Save' if @issue.new_record?%>
<% end %>

app/views/issues/edit.html.erb
<h4 class="project_heading"><%= @issue.title %></h4>

<div class="btn_row">
  <%=link_to 'Cancel', project_path(@project), class: 'create_btn cancel_btn' %>
  <%=link_to 'Save', 'javascript:void(0);', class: 'create_issue create_btn', onclick: "$('.issue_form').submit();" %>
  <%=link_to 'Delete issue', project_issue_path(@project, @issue), data: { "turbo-method": :delete }, class: 'create_btn' %>
</div>

<div class="box_wrapper issue_project_wrapper">
  <div class="form_heighlight">
    <div class="issue">Issue number: <%=@issue.id%> </div>
    <div class="creation">Creation date: <%=@issue.created_at.strftime("%Y-%m-%d")%></div>
  </div>

  <%=render 'form' %>

  <div class="comment_box">
    <h5>Comments</h5>

    <div id="comments_list">
      <%= render partial: "comment", collection: @issue.comments %>
    </div>

    <div class="field_comment">
      <label>Now</label>
      <%= text_field_tag 'comment[description]', nil, placeholder: 'Write a new comment here and it will be saved' %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#comment_description").on('focusout', function(){
    if ($(this).val() != ''){
      $.ajax({
        type: "POST",
        url: "<%=add_comment_project_issue_path(@project, @issue)%>",
        data: {'comment[description]': $(this).val()},
        dataType: "json",
        success: function(result){
          $("#comments_list").append("<div class='comment_row'><div class='time'>"+result.date+"</div><div class='text'>"+result.description+"</div></div>");
          $("#comment_description").val(null);
        }
      });
    }
  })
</script>

app/views/issues/new.html.erb
<h4 class="project_heading">Add new issue</h4>

<div class="box_wrapper">
  <%=render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>

  <body>
    <div class="app_header">
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete } %> 
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
    <div class="wrapper">
      <% flash.each do |type, msg| %>
        <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>

      <script type="text/javascript">
        setTimeout(function() {
            $('.alert').hide();
        }, 2500);
      </script>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <%= f.submit 'Save' %>
<% end %>

app/views/projects/edit.html.erb
<div class="box_wrapper">
  <h5>Edit Project</h5>
  <%=render 'form'%>
</div>

app/views/projects/index.html.erb
<h4 class="project_heading">Projects</h4>
<div class="btn_row">
  <%=link_to 'Create new project', new_project_path, class: 'create_btn' %>
</div>

<div class="box_wrapper issue_project_wrapper">
  <%if @projects.size > 0 %>
    <table class="projects_table">
      <thead>
        <th>Project Name</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td>
              <%=link_to project.name, project_path(project), class: 'project_name'%>
            </td>
            <td>
              <div class="drop_box">
                <%= link_to 'javascript:;', class: 'drop_btn' do %>
                  <%= image_tag 'dot.png', alt: 'dot', class: 'icon_dot' %>
                <% end %>
                <div class="dropdown">
                  <ul class="dropmenu">
                    <li><%=link_to 'Edit', edit_project_path(project) %></li>
                    <li><%=link_to 'Delete', project_path(project), data: { "turbo-method": :delete } %></li>
                  </ul>
                </div>
              </div>
            </td>
          </tr>
        <% end %> 
      </tbody>
    </table>
  <% else %>
    No project added
  <% end %>
</div>

<script type="text/javascript">
  $('.icon_dot').click(function() {
    // $('.dropdown').hide();
    $(this).closest('tr').find('.dropdown').toggle();
  });
</script>

app/views/projects/new.html.erb
<div class="box_wrapper">
  <h5>Add New Project</h5>
  <%=render 'form'%>
</div>

app/views/projects/show.html.erb
<h4 class="project_heading"><%=@project.name%></h4>

<div class="btn_row">
  <%=link_to 'Create a new issue', new_project_issue_path(@project), class: 'create_btn' %>
</div>

<div class="box_wrapper issue_project_wrapper">

  <% if @project.issues.size > 0 %>
    <table class="issue_table">
      <thead>
        <th>No</th>
        <th>Title</th>
        <th>Date created</th>
        <th>Assigned to</th>
        <th>Status</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% @project.issues.each do |issue| %>
          <tr>
            <td><%=issue.id%></td>
            <td><%=issue.title %></td>
            <td><%=issue.created_at.strftime("%Y-%m-%d")%></td>
            <td><%=issue.assign_to%></td>
            <td><%=issue.status.humanize%></td>
            <td>
              <div class="drop_box">
                  <%= link_to 'javascript:;', class: 'drop_btn' do %>
                    <%= image_tag 'dot.png', alt: 'dot', class: 'icon_dot' %>
                  <% end %>
                  <div class="dropdown">
                    <ul class="dropmenu">
                      <li><%=link_to 'Edit', edit_project_issue_path(@project, issue) %></li>
                      <li><%=link_to 'Delete', project_issue_path(@project, issue), data: { "turbo-method": :delete } %></li>
                    </ul>
                  </div>
                </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    No issue added for this project
  <% end %>
</div>

<script type="text/javascript">
  $('.icon_dot').click(function() {
    // $('.dropdown').hide();
    $(this).closest('tr').find('.dropdown').toggle();
  });
</script>